#! /bin/sh

sxhkd &
bspc monitor -d I II III IV V VI VII VIII IX
#bspc monitor HDMI-1 -d X
#bspc monitor HDMI-0 -d I II III
#bspc monitor DP-0 -s HDMI-0
#bspc monitor VGA1 -d X

bspc config border_width            1
bspc config window_gap              1

bspc config split_ratio             0.5
bspc config borderless_monocle      false
bspc config paddingless_monocle     false
bspc config gapless_monocle         false
bspc config focus_follows_pointer   true
bspc config split_ratio             0.5
bspc config bottom_padding          0
bspc config left_padding            0
bspc config right_padding           0
bspc config top_padding             0

bspc config normal_border_color "#18232F"
bspc config focused_border_color "#405F7B"
bspc config presel_feedback_color "#152636"
bspc config active_border_color "#FF00C5"

#kill
#killall zsh sh sleep panel4 stalonetray

#autostart
xrdb ~/.Xresources &
hsetroot -fill ~/image/walls/ronaldo-de-oliveira-683920-unsplash.jpg
~/lemon/panel4 &
sleep 3 && stalonetray &
notify-send -i ~/.config/dunst/sun.png "Bspwmrc Loaded" "Welcome home, <b>$USER</b>!"
parcellite -n &
