#! /bin/sh

sxhkd &
bspc monitor -d I II III IV V VI VII VIII IX 
#bspc monitor VGA1 -d X

bspc config border_width            2
bspc config window_gap              5

bspc config split_ratio             0.52
bspc config borderless_monocle      false
bspc config paddingless_monocle     false
bspc config gapless_monocle         false
bspc config focus_follows_pointer   true
bspc config split_ratio             0.5
bspc config bottom_padding          0
bspc config left_padding            0
bspc config right_padding           0
bspc config top_padding             0
#bspc rule -a Steam state=floating center=on
#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

bspc config normal_border_color "#18232F"
bspc config focused_border_color "#405F7B"
bspc config presel_feedback_color "#152636"
bspc config active_border_color "#FF00C5"
#source the colors.
#. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
# Use the line below if you are on bspwm >= 0.9.4
#bspc config presel_feedback_color "$color1"
# Use the line below if you are on bspwm < 0.9.4
#bspc config presel_border_color "$color1"

#kill
pkill panel3 &
pkill stalonetray &

#autostart
xrdb ~/.Xresources &
hsetroot -fill ~/image/walls/ronaldo-de-oliveira-683920-unsplash.jpg
~/lemon/panel3 &
sleep 3 && stalonetray &
#~/lemon/xexec &
notify-send -i ~/.config/dunst/sun.png " Bspwmrc Loaded" "     Welcome home, <b>$USER</b>!"
#sleep 3 && stalonetray &
#sleep 3 && bspc config top_padding 0
