#! /bin/sh

sxhkd &
bspc monitor -d I II III IV V VI VII VIII IX 
#bspc monitor VGA1 -d X

bspc config border_width            2
bspc config window_gap              5

bspc config split_ratio             0.52
bspc config borderless_monocle      false
bspc config paddingless_monocle     false
bspc config gapless_monocle         false
bspc config focus_follows_pointer   true
bspc config split_ratio             0.5
bspc config bottom_padding          0
bspc config left_padding            0
bspc config right_padding           0
bspc config top_padding             25 
#bspc rule -a Steam state=floating center=on
#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

#bspc config normal_border_color "#528588"
#bspc config focused_border_color "#dee3e0"
#bspc config presel_feedback_color "#2c3939"
#bspc config active_border_color "#333333"
#source the colors.
. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_border_color "$color3"
# Use the line below if you are on bspwm >= 0.9.4
#bspc config presel_feedback_color "$color1"
# Use the line below if you are on bspwm < 0.9.4
#bspc config presel_border_color "$color1"

#autostart
#wal -i image/walls/paul-gilmore-100296-unsplash.jpg
xrdb ~/.Xresources
hsetroot -fill ~/image/walls/paul-gilmore-100296-unsplash.jpg
stalonetray &
~/lemonbar/panel/panel &
compton --no-fading-openclose &
notify-send -i ~/.config/dunst/sun.png " Bspwmrc Loaded" "     Welcome home, <b>$USER</b>!"

